version: '3.9'

services:
  mariadb:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nation
      MYSQL_USER: nation
      MYSQL_PASSWORD: nation
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  mysql-8:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nation
      MYSQL_USER: nation
      MYSQL_PASSWORD: nation
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  mysql-5:
    image: mysql:5.7.42
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nation
      MYSQL_USER: nation
      MYSQL_PASSWORD: nation
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

