version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: testschema
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpwd
    volumes:
      - ./docker/mysql/config:/etc/mysql/conf.d
    ports:
      - 3306:3306
