version: '3.9'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
    volumes:
      - ./docker/mysql/config:/etc/mysql/conf.d
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
