# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Test and build with ant

on:
  push:
    branches:
      - master
      - dev/pitc-*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    services:
      # defines the postgres db service using Dockerfile-postgres. No data is loaded on startup
      mysql:
        image: mysql:5.7.36
        env:
          MYSQL_ROOT_PASSWORD: rootpwd
          MYSQL_DATABASE: testschema
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpwd
        volumes:
          - /home/runner/work/JdbcMySql/JdbcMySql/docker/mysql/config:/etc/mysql/conf.d
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install ant
        run: |
          sudo apt-get update
          sudo apt-get install ant
      - name: Tests with Ant
        run: ant -noinput -buildfile build.xml test
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml test build
