# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Test and build with ant

on:
  push:
    branches:
      - master
      - dev/pitc-*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7.36
        env:
          MYSQL_ROOT_PASSWORD: rootpwd
          MYSQL_DATABASE: testschema
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpwd
        options: >-
          -v /home/runner/work/JdbcMySql/JdbcMySql/docker/mysql/config:/etc/mysql/conf.d 
          --health-cmd="mysqladmin ping" 
          --health-interval=5s 
          --health-timeout=5s 
          --health-retries=3
        ports:
          - 3306:3306
    steps:
      - run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - run: /usr/bin/docker ps
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: ls -la /home/runner/work/JdbcMySql/JdbcMySql/docker/mysql/config
      - name: Tests with Ant
        run: ant -noinput -buildfile build.xml test
        continue-on-error: true
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: jdbc-tests.txt
          path: ./tmp/jdbc-tests.txt
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml build