name: Create and upload released

env:
  PROJECT_NAME: jdbcmysql

on:
  push:
    tags:
      - v*.**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set TAG-Env
        run: echo "NAME_TAG=${PROJECT_NAME}-${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Show current application version
        run: ./gradlew cV
      - name: Execute Gradle build
        run: ./gradlew build
      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.NAME_TAG }}
          path: build/libs/
          if-no-files-found: error
