name: Create and upload released

env:
  PROJECT_NAME: jdbcmysql

on:
  push:
    tags:
      - v*.**
    branches:
      - issue/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # Tests need a running DB instance
      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          # https://docs.docker.com/compose/reference/overview/
          cli-args: "up -d --build"
      - name: Sleep for 20 seconds # TODO: find a better way to wait until the database is ready
        run: sleep 20s
        shell: bash
      - name: check logs of docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          # https://docs.docker.com/compose/reference/overview/
          cli-args: "logs"
      - name: Verify MySQL connection from host with host 127.0.0.1
        run: |
          mysql --host 127.0.0.1 --port 3306 -uroot -prootpwd -e "SHOW DATABASES"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: snapshot
          path: build/libs/
          if-no-files-found: error
